// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNu2l4em4R_WEE8Lo1o4gpo2MCj7-Pbwc',
    appId: '1:363848646486:web:75427c24ea48a0283ba0f7',
    messagingSenderId: '363848646486',
    projectId: 'equigasto',
    authDomain: 'equigasto.firebaseapp.com',
    storageBucket: 'equigasto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZgwzxdq4eUn3diepj3HxgKaJ5xRx7Ep4',
    appId: '1:363848646486:android:421926d21e9a9c4a3ba0f7',
    messagingSenderId: '363848646486',
    projectId: 'equigasto',
    storageBucket: 'equigasto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_EhA_82v_eD-Gmm0nPVac6lnQdJxe4yU',
    appId: '1:363848646486:ios:b0f3061660ca43ce3ba0f7',
    messagingSenderId: '363848646486',
    projectId: 'equigasto',
    storageBucket: 'equigasto.firebasestorage.app',
    iosBundleId: 'com.sire.equigasto',
  );
}
